AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for RDS Proxy

Resources:
  RDSProxyRole:
    Type: 'AWS::IAM::Role'
    Condition: UseDatabaseProxyInProd
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: rds.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecretsManagerReadWrite'
      Tags:
        - Key: Name
          Value:
            'Fn::Sub': '${devEnvironment}-rds-proxy-role'
