AWSTemplateFormatVersion: '2010-09-09'
Description: S3 VPC gateway endpoint

Resources:
  S3Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      VpcId:
        Ref: WebScraperVPC
      ServiceName:
        'Fn::Sub': 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds:
        - Ref: PrivateRouteTable
