AWSTemplateFormatVersion: 2010-09-09
Description: >-
  WebScraper
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Lambda function that scrapes Ropewiki pages and stores them in the database
  RopewikiScraper:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that scrapes Ropewiki pages and stores them in the database
      Runtime: nodejs24.x
      Architectures:
      - x86_64
      Handler: src/ropewiki/main.ropewikiScraperHandler
      # This property associates this Lambda function with a scheduled CloudWatch Event. For all available properties, see
      # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
      # This runs once a week on Sunday at midnight UTC.
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * SUN *)
      MemorySize: 128
      Timeout: 100
# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
