version: 0.2

phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  pre_build:
    commands:
      # Discover and run unit tests
      - npm run test
      # Merge main template (main/*.yaml) before removing scripts
      - npm run merge:main-template
      # Remove all unit tests and scripts to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf ./test
      - rm -rf ./scripts
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
      - npm prune --production
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template cloudformation/stacks/mergedMainTemplate.yaml --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
