get:
  summary: List all routes
  description: Returns all routes in the database.
  operationId: getRoutes
  tags:
    - routes
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/route.yaml'
          examples:
            routesResponse:
              $ref: '../examples/routes-response.json'
    '500':
      description: Internal server error
