AWSTemplateFormatVersion: '2010-09-09'
Description: ECS task definition for generate route marker tiles Fargate task

Resources:
  GenerateRouteMarkerTilesTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family:
        'Fn::Sub': '${devEnvironment}-generate-route-marker-tiles'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '1024'
      Memory: '8192'
      ExecutionRoleArn:
        'Fn::GetAtt': GenerateRouteMarkerTilesExecutionRole.Arn
      TaskRoleArn:
        'Fn::GetAtt': GenerateRouteMarkerTilesTaskRole.Arn
      ContainerDefinitions:
        - Name: generate-route-marker-tiles
          Image:
            'Fn::Sub': '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${GenerateRouteMarkerTilesRepository}:latest'
          Essential: true
          Environment:
            - Name: DEV_ENVIRONMENT
              Value:
                Ref: devEnvironment
            - Name: DB_HOST
              Value:
                'Fn::If':
                  - UseDatabaseProxyInProd
                  - 'Fn::GetAtt': RDSProxy.Endpoint
                  - 'Fn::GetAtt': Database.Endpoint.Address
            - Name: DB_PORT
              Value:
                'Fn::GetAtt': Database.Endpoint.Port
            - Name: DB_NAME
              Value:
                'Fn::Sub': '${devEnvironment}db'
            - Name: DB_USER
              Value:
                Ref: DatabaseUsername
            - Name: DB_PASSWORD
              Value:
                Ref: DatabasePassword
            - Name: USE_DATABASE_PROXY
              Value:
                Ref: UseDatabaseProxy
            - Name: MAP_DATA_BUCKET_NAME
              Value:
                Ref: MapDataBucket
            - Name: CLOUDFRONT_DISTRIBUTION_ARN
              Value:
                'Fn::If':
                  - HasCloudFrontDistribution
                  - Ref: CloudFrontDistributionArn
                  - ''
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: GenerateRouteMarkerTilesLogGroup
              awslogs-region:
                Ref: 'AWS::Region'
              awslogs-stream-prefix: ecs
