AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repositories for Fargate task images

Resources:
  GenerateRouteMarkerTilesRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName:
        'Fn::Sub': '${devEnvironment}-generate-route-marker-tiles'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Keep last 2 images","selection":{"tagStatus":"any","countType":"imageCountMoreThan","countNumber":2},"action":{"type":"expire"}}]}
      ImageTagMutability: MUTABLE
      EmptyOnDelete: true
  GenerateTrailTilesRepository:
    Type: 'AWS::ECR::Repository'
    Properties:
      RepositoryName:
        'Fn::Sub': '${devEnvironment}-generate-trail-tiles'
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Keep last 2 images","selection":{"tagStatus":"any","countType":"imageCountMoreThan","countNumber":2},"action":{"type":"expire"}}]}
      ImageTagMutability: MUTABLE
      EmptyOnDelete: true
Outputs:
  GenerateRouteMarkerTilesRepositoryUri:
    Description: ECR repository URI for the generate route marker tiles task image (build and push with this tag)
    Value:
      'Fn::Sub': '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${GenerateRouteMarkerTilesRepository}:latest'
  GenerateTrailTilesRepositoryUri:
    Description: ECR repository URI for the generate trail tiles task image (build and push with this tag)
    Value:
      'Fn::Sub': '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${GenerateTrailTilesRepository}:latest'
