openapi: 3.0.1
info:
  title: WebScraper API
  description: REST API for the webscraper database.
  version: 1.0.0
  contact: {}

servers:
  - url: https://api.webscraper.ropegeo.com
    description: API Gateway base URL (override at deployment)

paths:
  /:
    $ref: './paths/getRootRedirect.yaml'
  /routes:
    $ref: './paths/getRoutes.yaml'
  /route/{routeId}/preview:
    $ref: './paths/getRoutePreview.yaml'
  /ropewiki/page/{id}:
    $ref: './paths/getRopewikiPageView.yaml'
  /search:
    $ref: './paths/search.yaml'
  /docs/{file}:
    $ref: './paths/getApiDocs.yaml'
  /mapdata/{path}:
    $ref: './paths/getMapData.yaml'

# API Gateway request validators (see https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-validation-set-up.html#api-gateway-request-validation-setup-importing-swagger)
x-amazon-apigateway-request-validators:
  all:
    validateRequestParameters: true
    validateRequestBody: true
  params-only:
    validateRequestParameters: true
    validateRequestBody: false
x-amazon-apigateway-request-validator: all
