AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway HTTP API and stage

Resources:
  WebScraperApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      BodyS3Location:
        Bucket:
          Ref: DocsBucketName
        Key: openapiResolved.yaml

  WebScraperApiStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: WebScraperApi
      StageName: $default
      AutoDeploy: true
      Description: Default stage for WebScraper HTTP API

Outputs:
  WebScraperApiEndpoint:
    Description: Default endpoint for the WebScraper HTTP API (use via CloudFront in production)
    Value:
      'Fn::GetAtt': [WebScraperApi, ApiEndpoint]
  WebScraperApiId:
    Description: API ID for the WebScraper HTTP API
    Value:
      Ref: WebScraperApi
  WebScraperApiStageName:
    Description: Stage name for the WebScraper HTTP API
    Value:
      Ref: WebScraperApiStage
