AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda that reprocesses Ropewiki routes on demand

Resources:
  RopewikiRouteReprocessor:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: A Lambda function that reprocesses Ropewiki routes on demand
      Runtime: nodejs22.x
      Architectures:
        - arm64
      CodeUri: ../../
      Handler: src/ropewiki/lambda-handlers/reprocessRoutesHandler.reprocessRoutesHandler
      MemorySize: 1024
      Timeout: 900
      VpcConfig:
        SecurityGroupIds:
          - Ref: LambdaSecurityGroup
        SubnetIds:
          - Ref: PrivateSubnet1
      Role:
        'Fn::GetAtt': RopewikiRouteReprocessorRole.Arn
      Environment:
        Variables:
          DEV_ENVIRONMENT:
            Ref: devEnvironment
          PROXY_URL:
            Ref: ProxyUrl
          DB_HOST:
            'Fn::If':
              - UseDatabaseProxyInProd
              - 'Fn::GetAtt': RDSProxy.Endpoint
              - 'Fn::GetAtt': Database.Endpoint.Address
          DB_PORT:
            'Fn::GetAtt': Database.Endpoint.Port
          USE_DATABASE_PROXY:
            Ref: UseDatabaseProxy
          DB_NAME:
            'Fn::Sub': '${devEnvironment}db'
          DB_USER:
            Ref: DatabaseUsername
          DB_PASSWORD:
            Ref: DatabasePassword
          MAP_DATA_PROCESSING_QUEUE_URL:
            Ref: MapDataProcessingQueue
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: esnext
        Sourcemap: true
        EntryPoints:
          - src/ropewiki/lambda-handlers/reprocessRoutesHandler.ts
